- name: Make sure we have a directory to store Vaultwarden's data
  ansible.builtin.file:
    path: files/vaultwarden/data
    state: directory
    mode: 700

- name: Downloading binary release file from github
  ansible.builtin.unarchive:
    src: https://github.com/czyt/vaultwarden-binary/releases/download/{{vaultwarden_version}}-extracted/vaultwarden-linux-{{vaultwarden_arch}}-extracted.zip
    dest: files
    remote_src: true
    creates: files/vaultwarden

- name: Configuring vaultwarden's environment variables
  ansible.builtin.template:
    src: templates/vaultwarden.env.j2
    dest: .config/vaultwarden.env
    mode: '600'

# MayFirst requires environment variables to be quoted in a non-standard way so
# we print out the string in the format they require so it can be easily copied
# and pasted into their control panel.
- name: Setting up administrator account, if the information was provided
  ansible.builtin.shell:
    cmd: |
      sed -e "s/\(.*\)'\(.*\)'/'\1\2'/g" -e 's/\(.*\)"\(.*\)"/"\1\2"/g' < .config/vaultwarden.env | awk '{ printf "%s ", $0 }
  register: env_var_string

- name: Printing out the environment variables to enter into MayFirst's scheduled job
  ansible.builtin.debug:
    msg: env_var_string.stdout
# https://help.mayfirst.org/en/guide/how-to-use-a-systemd-service-to-run-web-app
